import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class TablesService {
  invDef: Record<string, Record<string, InvAbilityDef>> = {};
  genDef: Record<string, GenAbilityDef> = {};
  get adjectives() { return t.adjectives; }
  get animals() { return t.animals; }
  get factions() { return t.factions; }
  get spheres() { return t.spheres; }
  get lifestyle() { return t.lifestyle; }
  get ability() { return t.ability; }

  constructor() {
    const inv = this.ability.investigative as any;
    const gen = this.ability.general as any;
    for (const c in inv) {
      this.invDef[c] = {};
      for (const a of inv[c]) {
        this.invDef[c][a] = new InvAbilityDef(a, c, a == "Spot Frailty" && c == "Warrior");
      }
    }
    for (const a in gen) {
      this.genDef[a] = new GenAbilityDef(a, gen[a][0], gen[a][1]);
    }
  }
}

const t = {
  adjectives: [
    "Accessible",
    "Active",
    "Adaptable",
    "Adventurous",
    "Agreeable",
    "Alert",
    "Amiable",
    "Anticipative",
    "Appreciative",
    "Articulate",
    "Aspiring",
    "Athletic",
    "Balanced",
    "Benevolent",
    "Brilliant",
    "Calm",
    "Capable",
    "Captivating",
    "Caring",
    "Challenging",
    "Charismatic",
    "Charming",
    "Cheerful",
    "Clear-headed",
    "Clever",
    "Colorful",
    "Companionable",
    "Compassionate",
    "Conciliatory",
    "Confident",
    "Conscientious",
    "Considerate",
    "Constant",
    "Contemplative",
    "Cooperative",
    "Courageous",
    "Courteous",
    "Creative",
    "Cultured",
    "Curious",
    "Daring",
    "Debonair",
    "Decent",
    "Decisive",
    "Dedicated",
    "Deep",
    "Dignified",
    "Directed",
    "Disciplined",
    "Discreet",
    "Dramatic",
    "Dutiful",
    "Dynamic",
    "Earnest",
    "Educated",
    "Efficient",
    "Elegant",
    "Eloquent",
    "Empathetic",
    "Energetic",
    "Enthusiastic",
    "Exciting",
    "Extraordinary",
    "Fair",
    "Faithful",
    "Firm",
    "Flexible",
    "Focused",
    "Forceful",
    "Forgiving",
    "Forthright",
    "Free-thinking",
    "Friendly",
    "Fun-loving",
    "Gallant",
    "Generous",
    "Gentle",
    "Genuine",
    "Good-natured",
    "Gracious",
    "Hardworking",
    "Healthy",
    "Hearty",
    "Helpful",
    "Heroic",
    "High-minded",
    "Honest",
    "Honorable",
    "Humble",
    "Humorous",
    "Idealistic",
    "Imaginative",
    "Impressive",
    "Incisive",
    "Incorruptible",
    "Independent",
    "Individualistic",
    "Innovative",
    "Inoffensive",
    "Insightful",
    "Intelligent",
    "Intuitive",
    "Kind",
    "Leisurely",
    "Liberal",
    "Logical",
    "Lovable",
    "Loyal",
    "Lyrical",
    "Magnanimous",
    "Manly",
    "Mature",
    "Methodical",
    "Meticulous",
    "Moderate",
    "Modest",
    "Neat",
    "Objective",
    "Observant",
    "Open",
    "Optimistic",
    "Orderly",
    "Organized",
    "Painstaking",
    "Passionate",
    "Patient",
    "Patriotic",
    "Peaceful",
    "Perceptive",
    "Perfectionist",
    "Personable",
    "Persuasive",
    "Playful",
    "Polished",
    "Popular",
    "Practical",
    "Precise",
    "Principled",
    "Profound",
    "Protective",
    "Prudent",
    "Punctual",
    "Purposeful",
    "Rational",
    "Realistic",
    "Reflective",
    "Relaxed",
    "Reliable",
    "Resourceful",
    "Respectful",
    "Responsible",
    "Reverential",
    "Romantic",
    "Rustic",
    "Sagely",
    "Scholarly",
    "Scrupulous",
    "Secure",
    "Selfless",
    "Self-critical",
    "Self-effacing",
    "Self-denying",
    "Self-reliant",
    "Self-sufficent",
    "Sensitive",
    "Sentimental",
    "Serious",
    "Sexy",
    "Sharing",
    "Shrewd",
    "Simple",
    "Skillful",
    "Sober",
    "Sociable",
    "Solid",
    "Sophisticated",
    "Spontaneous",
    "Sporting",
    "Stable",
    "Steadfast",
    "Steady",
    "Stoic",
    "Strong",
    "Studious",
    "Suave",
    "Subtle",
    "Sweet",
    "Sympathetic",
    "Systematic",
    "Tasteful",
    "Teacherly",
    "Thorough",
    "Tidy",
    "Tolerant",
    "Tractable",
    "Trusting",
    "Uncomplaining",
    "Understanding",
    "Upright",
    "Urbane",
    "Venturesome",
    "Visionary",
    "Vivacious",
    "Warm",
    "Well-bred",
    "Well-read",
    "Well-rounded",
    "Winning",
    "Wise",
    "Witty",
    "Youthful",
    "Absentminded",
    "Aggressive",
    "Ambitious",
    "Amusing",
    "Artful",
    "Ascetic",
    "Authoritarian",
    "Big-thinking",
    "Boyish",
    "Breezy",
    "Businesslike",
    "Casual",
    "Cerebral",
    "Chummy",
    "Circumspect",
    "Competitive",
    "Complex",
    "Confidential",
    "Conservative",
    "Contradictory",
    "Crisp",
    "Cute",
    "Deceptive",
    "Determined",
    "Dominating",
    "Dreamy",
    "Driven",
    "Droll",
    "Dry",
    "Earthy",
    "Effeminate",
    "Emotional",
    "Enigmatic",
    "Experimental",
    "Familial",
    "Folksy",
    "Formal",
    "Freewheeling",
    "Frugal",
    "Glamorous",
    "Guileless",
    "High-spirited",
    "Hurried",
    "Hypnotic",
    "Impassive",
    "Impersonal",
    "Impressionable",
    "Intense",
    "Irreligious",
    "Irreverent",
    "Maternal",
    "Mellow",
    "Modern",
    "Moralistic",
    "Mystical",
    "Neutral",
    "Noncommittal",
    "Noncompetitive",
    "Obedient",
    "Old-fashioned",
    "Ordinary",
    "Outspoken",
    "Paternalistic",
    "Physical",
    "Placid",
    "Political",
    "Predictable",
    "Preoccupied",
    "Private",
    "Progressive",
    "Proud",
    "Pure",
    "Questioning",
    "Quiet",
    "Religious",
    "Reserved",
    "Restrained",
    "Retiring",
    "Sarcastic",
    "Self-conscious",
    "Sensual",
    "Skeptical",
    "Smooth",
    "Soft",
    "Solemn",
    "Solitary",
    "Stern",
    "Stoic",
    "Strict",
    "Stubborn",
    "Stylish",
    "Surprising",
    "Soft",
    "Tough",
    "Unaggressive",
    "Unambitious",
    "Unceremonious",
    "Unchanging",
    "Undemanding",
    "Unfathomable",
    "Unhurried",
    "Uninhibited",
    "Unpatriotic",
    "Unpredictable",
    "Unsentimental",
    "Whimsical",
    "Abrasive",
    "Abrupt",
    "Aimless",
    "Airy",
    "Aloof",
    "Amoral",
    "Angry",
    "Anxious",
    "Apathetic",
    "Arbitrary",
    "Argumentative",
    "Arrogant",
    "Artificial",
    "Asocial",
    "Assertive",
    "Barbaric",
    "Bewildered",
    "Bizarre",
    "Bland",
    "Blunt",
    "Boisterous",
    "Brittle",
    "Brutal",
    "Calculating",
    "Callous",
    "Cantakerous",
    "Careless",
    "Cautious",
    "Charmless",
    "Childish",
    "Clumsy",
    "Coarse",
    "Cold",
    "Colorless",
    "Complacent",
    "Complaining",
    "Compulsive",
    "Conceited",
    "Condemnatory",
    "Conformist",
    "Confused",
    "Contemptible",
    "Conventional",
    "Cowardly",
    "Crafty",
    "Crass",
    "Crazy",
    "Criminal",
    "Critical",
    "Crude",
    "Cruel",
    "Cynical",
    "Decadent",
    "Deceitful",
    "Delicate",
    "Demanding",
    "Dependent",
    "Desperate",
    "Destructive",
    "Devious",
    "Difficult",
    "Dirty",
    "Disconcerting",
    "Discontented",
    "Discouraging",
    "Discourteous",
    "Dishonest",
    "Disloyal",
    "Disobedient",
    "Disorderly",
    "Disorganized",
    "Disputatious",
    "Disrespectful",
    "Disruptive",
    "Dissolute",
    "Dissonant",
    "Distractible",
    "Disturbing",
    "Dogmatic",
    "Domineering",
    "Dull",
    "Easily Discouraged",
    "Egocentric",
    "Enervated",
    "Envious",
    "Erratic",
    "Escapist",
    "Excitable",
    "Expedient",
    "Extravagant",
    "Extreme",
    "Faithless",
    "False",
    "Fanatical",
    "Fanciful",
    "Fatalistic",
    "Fawning",
    "Fearful",
    "Fickle",
    "Fiery",
    "Fixated",
    "Flamboyant",
    "Foolish",
    "Forgetful",
    "Fraudulent",
    "Frightening",
    "Frivolous",
    "Gloomy",
    "Graceless",
    "Grand",
    "Greedy",
    "Grim",
    "Gullible",
    "Hateful",
    "Haughty",
    "Hedonistic",
    "Hesitant",
    "Hidebound",
    "High-handed",
    "Hostile",
    "Ignorant",
    "Imitative",
    "Impatient",
    "Impractical",
    "Imprudent",
    "Impulsive",
    "Inconsiderate",
    "Incurious",
    "Indecisive",
    "Indulgent",
    "Inert",
    "Inhibited",
    "Insecure",
    "Insensitive",
    "Insincere",
    "Insulting",
    "Intolerant",
    "Irascible",
    "Irrational",
    "Irresponsible",
    "Irritable",
    "Lazy",
    "Libidinous",
    "Loquacious",
    "Malicious",
    "Mannerless",
    "Mawkish",
    "Mechanical",
    "Meddlesome",
    "Melancholic",
    "Messy",
    "Miserable",
    "Miserly",
    "Misguided",
    "Money-minded",
    "Monstrous",
    "Moody",
    "Morbid",
    "Muddle-headed",
    "Naive",
    "Narcissistic",
    "Narrow",
    "Narrow-minded",
    "Neglectful",
    "Neurotic",
    "Nihilistic",
    "Obnoxious",
    "Obsessive",
    "Obvious",
    "Odd",
    "Offhand",
    "Opinionated",
    "Opportunistic",
    "Oppressed",
    "Outrageous",
    "Overimaginative",
    "Paranoid",
    "Passive",
    "Pedantic",
    "Perverse",
    "Petty",
    "Plodding",
    "Pompous",
    "Possessive",
    "Power-hungry",
    "Predatory",
    "Prejudiced",
    "Presumptuous",
    "Pretentious",
    "Prim",
    "Procrastinating",
    "Profligate",
    "Provocative",
    "Pugnacious",
    "Puritanical",
    "Quirky",
    "Reactionary",
    "Reactive",
    "Regimental",
    "Regretful",
    "Repentant",
    "Repressed",
    "Resentful",
    "Ridiculous",
    "Rigid",
    "Ritualistic",
    "Rowdy",
    "Ruined",
    "Sadistic",
    "Sanctimonious",
    "Scheming",
    "Scornful",
    "Secretive",
    "Sedentary",
    "Selfish",
    "Self-indulgent",
    "Shallow",
    "Shortsighted",
    "Shy",
    "Silly",
    "Single-minded",
    "Sloppy",
    "Slow",
    "Sly",
    "Small-thinking",
    "Softheaded",
    "Sordid",
    "Steely",
    "Stiff",
    "Strong-willed",
    "Stupid",
    "Submissive",
    "Superficial",
    "Superstitious",
    "Suspicious",
    "Tactless",
    "Tasteless",
    "Tense",
    "Thoughtless",
    "Timid",
    "Transparent",
    "Treacherous",
    "Trendy",
    "Troublesome",
    "Unappreciative",
    "Uncaring",
    "Uncharitable",
    "Unconvincing",
    "Uncooperative",
    "Uncreative",
    "Uncritical",
    "Undisciplined",
    "Unfriendly",
    "Ungrateful",
    "Unhealthy",
    "Unimaginative",
    "Unimpressive",
    "Unlovable",
    "Unpolished",
    "Unprincipled",
    "Unrealistic",
    "Unreliable",
    "Unrestrained",
    "Unstable",
    "Vacuous",
    "Vague",
    "Venal",
    "Venomous",
    "Vindictive",
    "Vulnerable",
    "Weak",
    "Weak-willed",
    "Well-meaning",
    "Willful",
    "Wishful",
    "Zany",
  ],
  animals: [
    "Aquatic Mammals",
    "Bats",
    "Bears",
    "Bugs",
    "Burrowing Mammals",
    "Cats",
    "Cattle",
    "Crustaceans",
    "Dogs",
    "Fish",
    "Fowl",
    "Frogs and Toads",
    "Great Cats",
    "Herd Beasts",
    "Horses",
    "Lizards",
    "Primates",
    "Raptors",
    "Rodents",
    "Seabirds",
    "Snakes",
    "Songbirds",
    "Spiders",
    "Swine",
    "Wolves and Foxes",
  ],
  factions: [
    "Ancient Nobility",
    "Church of Denari",
    "City Watch",
    "Commoners",
    "Guild of Architects and Canal-Watchers",
    "Mercanti",
    "Mercenaries",
    "Monstrosities",
    "Outlanders",
    "Sorcerous Cabals",
    "Thieves' Guilds",
    "Triskadane",
  ],
  spheres: [
    ["Aging", true, true],
    ["Air", true, false],
    ["Animal", true, true],
    ["Blades", true, false],
    ["Blood", true, false],
    ["Chaos", true, true],
    ["Curses", true, true],
    ["Death", true, false],
    ["Decay/Entropy", true, false],
    ["Demonology", true, true],
    ["Disease", true, true],
    ["Earth", true, false],
    ["Fear", false, true],
    ["Fire", true, false],
    ["Flesh", true, false],
    ["Ghosts and Spirits", false, true],
    ["Ice", true, false],
    ["Illusion", false, true],
    ["Lightning", true, false],
    ["Love", false, true],
    ["Luck", true, true],
    ["Memory", false, true],
    ["Music", false, true],
    ["Necromancy", true, false],
    ["Physical Transmutation", true, false],
    ["Plants", true, false],
    ["Possession", true, true],
    ["Secrets", false, true],
    ["Shadow", true, false],
    ["Statuary", true, false],
    ["Swamp", true, false],
    ["Transmutation", true, false],
    ["Transportation", true, true],
    ["Water", true, false],
  ],
  lifestyle: [
    "Squalid",
    "Struggling",
    "Comfortable",
    "Wealthy",
    "Opulent",
  ],
  ability: {
    investigative: {
      Social: [
        "Charm",
        "Command",
        "Intimidation",
        "Liar’s Tell",
        "Nobility",
        "Servility",
        "Taunt",
        "Trustworthy",
      ],
      Sentinel: [
        "Felonious Intent",
        "Laws & Traditions",
        "Spirit Sight",
        "Vigilance",
      ],
      Sorcerer: [
        "Corruption",
        "Forgotten Lore",
        "Leechcraft",
        "Prophecy",
      ],
      Thief: [
        "City’s Secrets",
        "Ridiculous Luck",
        "Scurrilous Rumors",
        "Skulduggery",
      ],
      Warrior: [
        "Know Monstrosities",
        "Spot Frailty",
        "Tactics of Death",
        "Wilderness Mastery",
      ],
    },
    general: {
      Athletics: ["Dodge", false],
      'Bind Wounds': ["Plenty of Leeches", false],
      Burglary: ["Fast Hands", false],
      Preparedness: ["Flashback", false],
      Stealth: ["Where’d She Go?", false],
      Sorcery: ["Blast", true],
      Sway: ["Play to the Crowd", true],
      Warfare: ["Cleave", true],
    },
  }
};

class InvAbilityDef {
  name: string;
  category: string;
  healthMorale: boolean;
  constructor(name: string, category: string, healthMorale: boolean) {
    this.name = name;
    this.category = category;
    this.healthMorale = healthMorale;
  }
}

class GenAbilityDef {
  name: string;
  talent: string;
  combat: boolean;
  constructor(name: string, talent: string, combat: boolean) {
    this.name = name;
    this.talent = talent;
    this.combat = combat;
  }
}
